import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const albums = defineCollection({
  loader: glob({ pattern: '*/index.md', base: './content/albums' }),
  schema: z.object({
    storyId: z.string().min(1),
    title: z.string().min(1),
    /** When the photographs were made. Displayed above the title. */
    date: z.coerce.date(),
    /**
     * When the album went up. Orders the site and dates the feed, so a trip
     * posted long after the fact still arrives as new. Falls back to `date`.
     */
    published: z.coerce.date().optional(),
    location: z.string().min(1),
    /** Photos in display order. Membership is generated by photos:push. */
    photos: z.array(z.object({
      file: z.string().min(1),
      caption: z.string().optional(),
      alt: z.string().optional(),
    })).min(1),
    /** Card and social image. Defaults to the first photo. */
    cover: z.string().optional(),
    description: z.string().optional(),
    draft: z.boolean().default(false),
  }),
});

export const collections = { albums };
