import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const albumPhoto = z.object({
  file: z.string().min(1),
  caption: z.string().optional(),
  alt: z.string().optional(),
  forSale: z.boolean().optional(),
  /** USD, written for humans; converted to integer cents in the catalog. */
  price: z.number().positive().multipleOf(0.01).optional(),
  /** Reversible removal from public pages; fulfillment still retains it. */
  hidden: z.boolean().optional(),
  /** Explicit false removes the private fulfillment mapping. */
  catalog: z.boolean().optional(),
}).superRefine((photo, context) => {
  if (photo.forSale === true && photo.price === undefined) {
    context.addIssue({ code: 'custom', path: ['price'], message: 'a photo for sale needs a price' });
  }
  if (photo.forSale !== true && photo.price !== undefined) {
    context.addIssue({ code: 'custom', path: ['price'], message: 'price is only valid when forSale is true' });
  }
  if (photo.forSale === true && photo.hidden === true) {
    context.addIssue({ code: 'custom', path: ['forSale'], message: 'a hidden photo cannot be for sale' });
  }
  if (photo.forSale === true && photo.catalog === false) {
    context.addIssue({ code: 'custom', path: ['catalog'], message: 'a photo for sale must remain in the catalog' });
  }
});

const albums = defineCollection({
  loader: glob({ pattern: '*/index.md', base: './content/albums' }),
  schema: z.object({
    storyId: z.string().min(1),
    title: z.string().min(1),
    /** When the photographs were made. Displayed above the title. */
    date: z.coerce.date(),
    /**
     * When the album went up. Orders the site and dates the feed, so a trip
     * posted long after the fact still arrives as new. Falls back to `date`.
     */
    published: z.coerce.date().optional(),
    location: z.string().min(1),
    /** Photos in display order. Membership is generated by photos:push. */
    photos: z.array(albumPhoto).min(1),
    /** Card and social image. Defaults to the first photo. */
    cover: z.string().optional(),
    description: z.string().optional(),
    draft: z.boolean().default(false),
  }),
});

export const collections = { albums };
