import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';
import { isPhotoId } from './lib/downloads';

const albumPhoto = z.object({
  /** Display name and sort position. Cosmetic — renaming changes nothing else. */
  file: z.string().min(1),
  /** Permanent identity, minted by photos:push. Joins frontmatter to the
   * manifest, names the S3 master, and is what an order records. */
  photoId: z.string().refine(isPhotoId, 'must look like photo_<24 hex characters>'),
  caption: z.string().optional(),
  alt: z.string().optional(),
  /** USD, written for humans; converted to integer cents in the catalog.
   * Its presence is what puts the photograph on sale. */
  price: z.number().positive().multipleOf(0.01).optional(),
  /** Off the album and out of the store, bytes retained. Reversible. */
  removed: z.coerce.date().optional(),
  /** Bytes purged. The entry stays behind as the record that it existed. */
  deleted: z.coerce.date().optional(),
}).superRefine((photo, context) => {
  if (photo.price !== undefined && photo.removed) {
    context.addIssue({ code: 'custom', path: ['price'], message: 'a removed photo cannot be for sale' });
  }
  if (photo.deleted && !photo.removed) {
    context.addIssue({ code: 'custom', path: ['deleted'], message: 'a photo must be removed before it is deleted' });
  }
});

const albums = defineCollection({
  loader: glob({ pattern: '*/index.md', base: './content/albums' }),
  schema: z.object({
    storyId: z.string().min(1),
    title: z.string().min(1),
    /** When the photographs were made. Displayed above the title. */
    date: z.coerce.date(),
    /**
     * When the album went up. Orders the site and dates the feed, so a trip
     * posted long after the fact still arrives as new. Falls back to `date`.
     */
    published: z.coerce.date().optional(),
    location: z.string().min(1),
    /** Photos in display order. Membership is generated by photos:push. */
    photos: z.array(albumPhoto).min(1),
    /** Card and social image. Defaults to the first photo. */
    cover: z.string().optional(),
    description: z.string().optional(),
    draft: z.boolean().default(false),
  }),
});

export const collections = { albums };
